global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "tunisia-energy-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["172.27.128.1:8000"]
        labels:
          app: "tunisia-energy-rag"
